version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    steps:
      - checkout

      - run:
          name: Update Environment
          command: 'apt update && apt-get upgrade --assume-yes'

      - run:
          name: Setup Build Tools
          command: 'apt install build-essential pkg-config qtchooser'
      - run:
          name: Install Libraries
          command: 'apt install qt5-default libqt5svg5-dev qtmultimedia5-dev \
          libavutil-dev libavformat-dev libavcodec-dev libavfilter-dev libavutil-dev libswscale-dev'

      - run:
          name: Print the Current Time
          command: date