version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    steps:
      - checkout

      - run:
          name: Update Environment
          command: 'apt update' #&& apt-get upgrade --assume-yes'

      - run:
          name: Setup Build Tools
          command: 'apt install --assume-yes build-essential pkg-config qtchooser'
      - run:
          name: Install Libraries
          command: 'apt install --assume-yes qt5-default libqt5svg5-dev qtmultimedia5-dev libavutil-dev libavformat-dev libavcodec-dev libavfilter-dev libavutil-dev libswscale-dev'

      - run:
          name: Configure Build
          command: 'qmake CONFIG+="debug"'
      - run:
          name: Build Chestnut
          command: 'make -j4'

      - run:
          name: Configure UnitTest build
          command: 'qmake CONFIG+="debug unittests"'

      - run:
          name: Build UnitTests
          command: 'make -j4'

      - #run:
        #  name: Run UnitTests
        #  command: './unittests/build/debug/chestnut_ut'
