version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    steps:
      - checkout

      - run:
          name: Update Environment
          command: 'apt update'

      - run:
          name: Setup Build Tools
          command: 'apt install --assume-yes build-essential pkg-config qtchooser wget unzip'
      - run:
          name: Install Libraries
          command: 'apt install --assume-yes qt5-default libqt5svg5-dev qtmultimedia5-dev libavutil-dev libavformat-dev libavcodec-dev libavfilter-dev libavutil-dev libswscale-dev'

      - run:
          name: Configure Build
          command: 'qmake CONFIG+="debug"'
      - run:
          name: Build Chestnut
          command: 'make -j4'

      - run:
          name: Configure UnitTest build
          command: 'qmake CONFIG+="debug unittests"'

      - run:
          name: Build UnitTests
          command: 'make -j4'

      # Could be done in parallel with build
      - run:
          name: Setup Sonar Scanner
          command: 'pushd scripts && chmod +x setupSonarScanner.sh && ./setupSonarScanner.sh && popd'

      - run:
          name: Run Static Analysis
          command: './scripts/static_analysis.sh'

      - run: 
          name: AppImage Build
          command: 'cd packaging/appimage/ && ../../third_party/pkg2appimage  chestnut.yml'

      - store_artifacts:
          path: 'packaging/appimage/out/Chestnut-.glibc2.14-x86_64.AppImage'
